spring:
  application:
    name: loom-etl-uploader
  batch:
    job:
      enabled: false
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

logging:
  level:
    io:
      awspring:
        cloud: debug

app:
  sqs:
    weather-summary-topic: loom-etl-queue
  weather-api:
    root-uri: https://api.open-meteo.com/v1
  s3:
    output-path: s3://etl-weather/output/${CURRENT_DATE}.csv
